### ISSUE TITLE
VNF resource consumption

### ISSUE THREAD

**Issue by qarawlus** [RealVNF/coordination-simulation#54]
Right now the node capacities are fixed number. Once a flow arrives at the node, the flow's data rate is deducted from the node's capacity regardless of the SF that it is being processed at.

Since this model is not realistic, the next step is to add non-fixed capacity handling. In this non-fixed context, the deduction from the node's capacity should be done via a function based on several parameters and should also be per SF. 

My initial thoughts regarding this are as follows:
- Nodes have fixed capacity numbers (e.g. simulating real fixed CPU capacity or Memory capacity).
- Each SF has a defined idle resource consumption figure to simulate that placed SFs actually consume resources even without processing flows.
- Once a flow arrives to an SF, it's data rate is passed to a function defined within the SF definition, and the resulting resource consumption figure is then deducted from the node's capacity. 
- Another idea is to also define the SF processing delays in relation to the node's capacity. This means that higher capacity nodes have lower processing delays for the SFs than nodes with lower capacity. 
- Another idea is to specify maximum capacity cap for each SF so that it does not consume more than it is allowed to.

**Comment by stefanbschneider** [comment]
@ldklenner @qarawlus Let's use this issue to agree on how to implement individual VNF resource consumptions. Once this is clear, we can still see who needs it first/who'll implement it.

**Comment by stefanbschneider** [comment]
My approach would be, as sketched above, to extend the yaml file defining the service and SFs to optionally include a path to a Python module that defines a resource consumption function. Eg,

```yaml
...

sf_list:
  a:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
    resource_module: 'resource_consumption_a.py'
  b:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
    resource_module: 'resource_consumption_b.py'
  c:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
```

Then we could use `importlib` do load the Python module dynamically: https://docs.python.org/3/library/importlib.html#importlib.import_module or https://stackoverflow.com/a/46483074/2745116

In the python module, there should be a function `def sf_resource_req(load)` that returns the required resources depending on the data rate/load. If no such function is defined in the yaml, we should use a simple linear model as default.

The returned resource requirements would then be used to check against the remaining node resources instead of the flow data rate: https://github.com/RealVNF/coordination-simulation/blob/master/src/coordsim/simulation/flowsimulator.py#L196

For now, we should start with a single node resource.

For now,

**Comment by stefanbschneider** [comment]
An alternative, which is probably simpler than individual Python modules per SF, we could also define a single Python module for all SFs like so:

```yaml
sf_list:
  a:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
  b:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
  c:
    processing_delay_mean: 5.0
    processing_delay_stdev: 0.0
sf_resource_req_module: "sfc1_resource_req.py"
```

Then inside the module, the function would need to return the required resources based on the load *and the specified SF name*: `def sf_resource_req(sf, load)`.
It should still work without defining any Python module.

This would be simpler as we only need to write, specify, and import a single Python module.
